### ISSUE TITLE
Question about lsystems

### ISSUE THREAD

**Issue by sonoro1234** [prideout/par#14]
Hi,

I have made a luajit ffi wrapping for par_shapes. Great for generating meshes!!
I would like to better understand par_shapes_create_lsystem.
Could you explain the actions done by shape tube and shape connect?

Thanks
victor bombi

**Comment by sonoro1234** [comment]
I have noticed than "shape connect" and "shape connect " produce different results

**Comment by prideout** [comment]
Hi Victor, I apologize for the lsystem stuff, I cranked it out way too quickly.  As you noticed, it doesn't even have very good parsing.

"shape connect" is a special command that is not allowed at the root, because it requires a previous shape to exist.  It creates a single ring of verts and connects them to the previous shape, which helps reduce mesh size.

If the shape type is anything other than "connect" (eg, "tube" or "connect   "), then an independent cylinder shape is inserted into the mesh.

This is definitely an area of par_shapes that needs improvement.

**Comment by sonoro1234** [comment]
Hi Philip,

Please dont apologize for free (and good) stuff.
Perhaps I would prefer  to develop lsystem with lua.
For connecting last points from scene to first points in newtube I think that par_shapes.h:1099 should be
```
	memcpy(newpts, cylinder->points ,sizeof(float) * (slices + 1) * 3);
instead of
    memcpy(newpts, cylinder->points + (slices + 1) * 3,sizeof(float) * (slices + 1) * 3);

```
